[package]
name = "neo4rs_include_snippet"
version = "0.9.0-rc.8"
edition = "2021"
description = "Internal proc macro for the include_snippet! macro"
rust-version = "1.85"
publish = true

[lib]
proc-macro = true

[dependencies]
unsynn = { version = "0.2.1", default-features = false }
